server:
  port: 8080

logging:
  level:
    org.springframework.web: DEBUG
    #  pattern:
    #    level: "[%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"

spring:
  application.name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"  # Cambia esto al origen permitido
            allowedMethods: "*"
            allowedHeaders: "*"  # Permitir todas las cabeceras
      #default-filters:
      #  - PrefixPath=/api  # Este es el prefijo global para todas las rutas
      routes:
        - id: service-almacen
          uri: http://localhost:8081
          predicates:
            - Path= /almacen/**
          filters:
            - StripPrefix=1
#        Aca iria lo de Maxi
#        - id: resources-service-route-notificaciones
#          uri: http://localhost:8081
#          predicates:
#            - Path=/notificaciones/**
#          filters:
#            - StripPrefix=1



# disable eureka by default
eureka:
  client:
    enabled: false